### ISSUE TITLE
Remove activeItem from form submission

### ISSUE THREAD

**Issue by craigsweaton** [chingu-voyage4/Geckos-Team-26#21]
activeItem state is being sent to the server in a post request for signup.

**Comment by 8thDay** [comment]
I'll take a look.

**Comment by 8thDay** [comment]
See PR #23 for proposed fix.

Wraps user info in an object, and sends only that object in the POST request.

**Comment by GarrusNapp** [comment]
PR #25 as an alternative fix.

**Comment by 8thDay** [comment]
PR #25 resolves this issue.
