### ISSUE TITLE
Re-position text in hero section of homepage

### ISSUE THREAD

**Issue by 8thDay** [chingu-voyage4/Geckos-Team-26#38]
The text is displaying over the face of the cute little guy on the homepage, for some screen sizes.

It would be nice to have it positioned cleanly over the yellow background, to the left of the image on landscape views, and either above or below the image on portrait views.

Interestingly, IE11 comes the closest to this atm!

**Comment by mairamartinsk** [comment]
Thanks for noticing this! We are serving two images, one horizontal and one vertical, depending on user's device. It should be easy enough to change text position depending on image displayed. I'll fix this as soon as I am done with the pet display component.   :)

**Comment by mairamartinsk** [comment]
Fixed on PR #47
